### ISSUE TITLE
Same results for the last four runs

### ISSUE THREAD

**Issue by null-xyj** [qitianwu/NodeFormer#17]
Hello, I've encountered an issue while running the model on the official splits of Cora, CiteSeer, and Pubmed. Despite conducting five separate runs, the results for the last four runs are identical. I have meticulously ensured that the parameters are reset at the beginning of each run. Could this be a mere coincidence, or might there be an underlying error that I'm missing?

**Comment by qitianwu** [comment]
Does this phenomenon happen for three datasets and different machines? If not, it might be caused by a coincidence. Maybe one can also try increasing the number of runs, and see what happen for the other separate runs.
