### ISSUE TITLE
Deezer Europe Dataset on SGFormer/NodeFormer

### ISSUE THREAD

**Issue by ryandeng1** [qitianwu/NodeFormer#19]
Hi,

In the SGFormer paper, that paper claims that NodeFormer achieves a 66% test accuracy on the DeezerEurope dataset, whereas on the NodeFormer paper, the paper claims that NodeFormer achieves a 71% test accuracy on the DeezerEurope dataset.

Which one is accurate, and what is the reason for the discrepancy? I ran the NodeFormer code on the DeezerEurope dataset and got around 71% test accuracy.

Thanks

**Comment by qitianwu** [comment]
Hi,

As explictly indicated in our papers, for NodeFormer, we use ROC-AUC as the evaluation metric on DeezerEurope, and for SGFormer, we use Accuracy.

**Comment by ryandeng1** [comment]
Thank you, I missed that when reading the paper.
