### ISSUE TITLE
Clarification on Visualization Techniques for Graphs 4 and 7 under Linear Complexity Constraints

### ISSUE THREAD

**Issue by FarisXiong** [qitianwu/NodeFormer#21]
I am currently examining the methodologies presented in your paper and am unclear about the techniques used to visualize Graphs 4 and 7 under linear complexity constraints. According to Equation 7, it seems infeasible to compute the attention scores between any two nodes using a linear approximation.
Could you please clarify the specific approach utilized for these visualizations under the mentioned constraints? Additionally, if there are any potential modifications or alternative methods that could be recommended to handle these calculations more feasibly, I would appreciate your insights.

$$z_{(l+1)u} \approx \frac{\phi(q_{u}/\sqrt{\tau})^T\sum_{\nu=1}^N  e^{g_{\nu}/\tau} \phi(k_{\nu}/\sqrt{\tau})  v_{\nu}^T}{\phi(q_{u}/\sqrt{\tau})^T\sum_{\omega=1}^N  e^{g_{\omega}/\tau} \phi(k_{\omega}/\sqrt{\tau}) }
$$

![image](https://github.com/qitianwu/NodeFormer/assets/55704024/e90c6d25-937d-4cfb-84af-0a1ec79044e2)

![image](https://github.com/qitianwu/NodeFormer/assets/55704024/63ec2713-e4f7-4c77-9ff8-6770bdfbb471)

**Comment by qitianwu** [comment]
Hi, thanks for your interest on our work. Actually our proposed approach is to accelerate the model computation for training and inference that does not require visualization of the intermediate results. if one needs to obtain the N*N attention matrix for visualization, one has to explictly calculate the all-pair weights. There is no algorithm for detouring the quadratic complexity in this case. 

For how to obtain the N*N attention matrix, one can simply modify our code. Though we do not provide the version for NodeFormer, here is our implementation for DIFFormer which can be a helpful reference:

https://github.com/qitianwu/DIFFormer/blob/d65842bc42532d13d526ab21b3ff2591c61b5a0e/node%20classification/difformer.py#L42-L43

**Comment by FarisXiong** [comment]
Thank you for your response and the solution you provided! 
I really appreciate your help.
