### ISSUE TITLE
Is the relatinoal bias still calculated in w/o graph circumstances?

### ISSUE THREAD

**Issue by AaronNing** [qitianwu/NodeFormer#4]
Hi Qitian,
 
Thanks for this fantastic work! 

In `nodeformer.py` line 284:
```python
        # compute update by relational bias of input adjacency, requires O(E)
        for i in range(self.rb_order):
            z_next += add_conv_relational_bias(value, adjs[i], self.b[i], self.rb_trans)
```

I am a little bit confused that, in w/o graph circumstances (e.g. #2 ,) is the relatinoal bias still calculated?
Thanks.

**Comment by qitianwu** [comment]
Hi Weixi,

In the w/o graph circumstances you mentioned, the relational bias is not used since we set rb_order=0 (see the [run.sh](https://github.com/qitianwu/NodeFormer/blob/b7b97a3a9a8d0976e6550a85e947faaa0508a3f7/run.sh#L44-L47) for detailed hyper-parameter settings)

**Comment by AaronNing** [comment]
I see. Thanks for your quick reply : )
