### ISSUE TITLE
Accurate scores of Figure 2 in the paper

### ISSUE THREAD

**Issue by AimeJiayue** [qitianwu/NodeFormer#6]
Hi, your paper is interesting and I would like to follow-up your work. But I noticed that when it comes to the experiment on cora, citeseer, deezer-europe and actor (Figure2 in the paper) there are only plots but not the accurate scores. Would it be convenient to share the accurate scores used for plotting? Thanks in advance.

**Comment by qitianwu** [comment]
Hi, the exact scores of Fig. 2 are presented in the result table of our Readme.md on the first page.

See here:
https://github.com/qitianwu/NodeFormer#key-results

**Comment by AimeJiayue** [comment]
Hello, I apologize if I didn't express my question clearly. What I would like to know is the scores of the all the models (all the models used to draw the graph, including GCN, dropedge, etc., except the Nodeformer) on those four datasets. This would allow us to follow-up your work, thanks a lot!

**Comment by qitianwu** [comment]
OK I see. I have uploaded the script for plotting the figure where the testing scores are contained.

See the `plot_main.ipynb` in the main branch:
https://github.com/qitianwu/NodeFormer/blob/main/plot_main.ipynb

**Comment by AimeJiayue** [comment]
It was really kind of you, thanks a lot.
