### ISSUE TITLE
Code without inductive settings????

### ISSUE THREAD

**Issue by tony-wl** [qitianwu/NodeFormer#9]
Hello, you explained in the experiment of your paper that this is an inductive setting, but I did not see the code for the inference stage of unknown nodes in the inductive setting. Do you have this code?

**Comment by qitianwu** [comment]
Hi, we did not claim the inductive setting in our paper, though the model is applicable for inductive setting. You can simply modify our codes (e.g., dataset.py) to change the graph data for training/inference.
